const MAX_NUMBER_OF_PRODUCTS_DISPLAYED = 15;
const MAX_NUMBER_OF_PRODUCTS = 100;
const lang = 'en-US';
const MIN_CHAR_CODE = 97;
const MAX_CHAR_CODE = 122;
const CURRENCY = 'EUR';
const MS_IN_SEC = 1000;
const TEN_MINS_IN_MS = 600000;
export {
  MAX_NUMBER_OF_PRODUCTS_DISPLAYED,
  MAX_NUMBER_OF_PRODUCTS,
  lang,
  MIN_CHAR_CODE,
  MAX_CHAR_CODE,
  CURRENCY,
  MS_IN_SEC,
  TEN_MINS_IN_MS,
};
