const MAX_NUMBER_OF_PRODUCTS_DISPLAYED = 100;
const lang = 'en-US';
const MIN_CHAR_CODE = 97;
const MAX_CHAR_CODE = 122;
export { MAX_NUMBER_OF_PRODUCTS_DISPLAYED, lang, MIN_CHAR_CODE, MAX_CHAR_CODE };
